# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!
target 'Instagram-Proj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Instagram-Proj
  pod 'Firebase/Analytics', :inhibit_warnings =>
   true
  pod 'Firebase/Auth', :inhibit_warnings =>
   true
  
  pod 'Firebase/Firestore', :inhibit_warnings =>
   true
  pod 'FirebaseFirestoreSwift', :inhibit_warnings =>
   true
  pod 'Kingfisher', :inhibit_warnings =>
   true
  pod 'Firebase/Storage', :inhibit_warnings =>
   true

  target 'Instagram-ProjTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
